import type { VocabItem } from "./types";

// Topic-specific content for A1 offline mock classes.
// Keys are lower-cased normalised topic names.

interface A1MockContent {
  vocab: VocabItem[];
  warmUpQuestions: string[];
  warmUpQuestionsPt: string[];
  sentenceFrames: string[];
  rolePlayScenario: string;
  rolePlayRoles: string[];
  practicePrompts: string[];
  grammarPoints: string[];
  grammarNote: string;
}

const v = (
  term: string,
  meaning: string,
  meaningPt: string,
  example: string,
): VocabItem => ({ term, meaning, meaningPt, example, isIdiom: false, literalMeaning: "" });

const A1_CONTENT: Record<string, A1MockContent> = {
  "greetings & introductions": {
    vocab: [
      v("Hello / Hi", "a common greeting", "Olá / Oi", "Hello! My name is Ana."),
      v("Good morning", "greeting used in the morning", "Bom dia", "Good morning! How are you?"),
      v("Good afternoon", "greeting used in the afternoon", "Boa tarde", "Good afternoon, everyone!"),
      v("My name is ___", "how you say your name", "Meu nome é ___", "My name is Carlos. Nice to meet you!"),
      v("Nice to meet you", "said when meeting someone new", "Prazer em conhecer você", "This is my friend Bia. Nice to meet you!"),
      v("How are you?", "question about someone's wellbeing", "Como você está?", "Hello! How are you today?"),
      v("I'm fine / I'm good", "common answer to 'How are you?'", "Estou bem", "I'm fine, thank you! And you?"),
      v("Goodbye / Bye", "said when leaving", "Tchau / Adeus", "It was nice to meet you. Goodbye!"),
      v("I'm from ___", "how you say where you are from", "Eu sou de ___", "I'm from Brazil. Where are you from?"),
      v("And you?", "asking the same question back", "E você?", "I'm good. And you?"),
    ],
    warmUpQuestions: [
      "What is your name?",
      "Where are you from?",
      "How old are you?",
      "How do you say 'Olá' in English?",
      "How do you greet a friend in Brazil?",
    ],
    warmUpQuestionsPt: [
      "Qual é o seu nome?",
      "De onde você é?",
      "Quantos anos você tem?",
      "Como se diz 'Olá' em inglês?",
      "Como você cumprimenta um amigo no Brasil?",
    ],
    sentenceFrames: [
      "Hello! My name is ___.",
      "I am from ___.",
      "Nice to meet you! I am ___.",
      "How are you? — I am ___.",
      "Goodbye! See you ___.",
    ],
    rolePlayScenario: "You meet a new classmate on the first day of English class. Greet them, say your name, and ask two questions.",
    rolePlayRoles: ["New student", "Classmate"],
    practicePrompts: [
      "Say: 'Hello, my name is ___. I am from ___. Nice to meet you!'",
      "Complete: 'Good ___, how ___ you?'",
      "Introduce a friend: 'This is ___. He/She is from ___.'",
      "Say goodbye: use 'Goodbye' or 'Bye' in a sentence.",
      "Answer out loud: 'How are you?' — use two words.",
    ],
    grammarPoints: ["Verb to be (am/is)", "Personal pronouns (I, you, he, she)", "Possessives (my, your)"],
    grammarNote: "Use **am** with 'I' and **is** with he/she/it: *I am Ana. She is my friend.* **My** and **your** show who something belongs to — *My name is..., What is your name?*",
  },

  "my family": {
    vocab: [
      v("mother / mum", "your female parent", "mãe / mamãe", "My mother is a teacher."),
      v("father / dad", "your male parent", "pai / papai", "My father works in the city."),
      v("sister", "a girl from the same parents", "irmã", "I have one sister. Her name is Bia."),
      v("brother", "a boy from the same parents", "irmão", "My brother is ten years old."),
      v("grandmother / grandma", "your parent's mother", "avó / vovó", "My grandmother lives with us."),
      v("grandfather / grandpa", "your parent's father", "avô / vovô", "My grandfather has a big garden."),
      v("aunt", "your parent's sister", "tia", "My aunt makes delicious food."),
      v("uncle", "your parent's brother", "tio", "My uncle is very funny."),
      v("baby", "a very young child", "bebê", "My cousin is a baby. She is six months old."),
      v("old / young", "age description", "velho(a) / jovem", "My grandmother is old. My sister is young."),
    ],
    warmUpQuestions: [
      "How many people are in your family?",
      "Do you have brothers or sisters?",
      "What is your mother's name?",
      "Do you live with your grandparents?",
      "Who is your favourite person in your family?",
    ],
    warmUpQuestionsPt: [
      "Quantas pessoas há na sua família?",
      "Você tem irmãos ou irmãs?",
      "Qual é o nome da sua mãe?",
      "Você mora com seus avós?",
      "Quem é a sua pessoa favorita na família?",
    ],
    sentenceFrames: [
      "My ___ is/are ___.",
      "I have ___ brother(s) and ___ sister(s).",
      "My mother's name is ___.",
      "My father is a ___.",
      "My family is ___.",
    ],
    rolePlayScenario: "Show a family photo to your teacher. Point to each person and say who they are.",
    rolePlayRoles: ["Student (showing the photo)", "Teacher (asking questions)"],
    practicePrompts: [
      "Say: 'I have ___ people in my family.'",
      "Name three family members and say one thing about each.",
      "Complete: 'My ___ is ___ years old.'",
      "Say who is old and who is young in your family.",
      "Complete: 'My favourite family member is ___ because ___.'",
    ],
    grammarPoints: ["Verb to be (is/are)", "Possessives (my, his, her)", "Numbers"],
    grammarNote: "Use **is** for one person and **are** for more than one: *My sister is tall. My brothers are funny.* **My** means belonging to me — *my mother, my brother, my family.*",
  },

  "numbers & colours": {
    vocab: [
      v("one / two / three", "basic numbers", "um / dois / três", "I have two brothers and one sister."),
      v("four / five / six", "numbers 4–6", "quatro / cinco / seis", "I am six years old — no, I am twenty-six!"),
      v("ten / twenty / one hundred", "bigger numbers", "dez / vinte / cem", "There are twenty students in the class."),
      v("red", "the colour of fire", "vermelho", "I have a red jacket."),
      v("blue", "the colour of the sky", "azul", "The sky is blue today."),
      v("green", "the colour of grass", "verde", "I like green apples."),
      v("yellow", "the colour of the sun", "amarelo", "My pencil is yellow."),
      v("white", "the colour of snow", "branco", "She is wearing a white dress."),
      v("black", "the colour of night", "preto", "My cat is black."),
      v("How many?", "question about quantity", "Quantos/Quantas?", "How many books do you have?"),
    ],
    warmUpQuestions: [
      "What is your favourite colour?",
      "How many people are in your family?",
      "What colour is your bag today?",
      "How old are you?",
      "Can you count from one to ten in English?",
    ],
    warmUpQuestionsPt: [
      "Qual é a sua cor favorita?",
      "Quantas pessoas há na sua família?",
      "De que cor é a sua bolsa hoje?",
      "Quantos anos você tem?",
      "Você consegue contar de um a dez em inglês?",
    ],
    sentenceFrames: [
      "My favourite colour is ___.",
      "I have ___ ___ (colour + object).",
      "There are ___ ___ in the room.",
      "I am ___ years old.",
      "The ___ is ___. (object + colour)",
    ],
    rolePlayScenario: "You are a shop assistant. A customer wants to buy something in a specific colour and quantity. Help them.",
    rolePlayRoles: ["Shop assistant", "Customer"],
    practicePrompts: [
      "Count from 1 to 10 out loud.",
      "Look around the room. Name three things and say their colour.",
      "Say your age, phone number digits, or house number in English.",
      "Complete: 'I have ___ ___ in my bag.' (number + object)",
      "Say your favourite colour and one thing that colour.",
    ],
    grammarPoints: ["Numbers 1–100", "Colours as adjectives", "Verb to have (have/has)", "How many?"],
    grammarNote: "In English, **adjectives come BEFORE the noun**: *a red bag* (not *a bag red*). Use **have** with I/you/they and **has** with he/she/it: *I have a blue pen. She has a red phone.*",
  },

  "daily routines": {
    vocab: [
      v("wake up", "to stop sleeping and open your eyes", "acordar", "I wake up at 7 o'clock every day."),
      v("have breakfast", "to eat your morning meal", "tomar café da manhã", "I have breakfast at 7:30."),
      v("go to school / work", "to travel to school or work", "ir para a escola / trabalho", "I go to school by bus."),
      v("have lunch", "to eat your midday meal", "almoçar", "I have lunch at 12 o'clock."),
      v("come home", "to return to your house", "chegar em casa", "I come home at 5 in the afternoon."),
      v("have dinner", "to eat your evening meal", "jantar", "My family has dinner at 7 p.m."),
      v("brush my teeth", "to clean your teeth with a toothbrush", "escovar os dentes", "I brush my teeth before bed."),
      v("go to bed / sleep", "to lie down and rest at night", "ir dormir / dormir", "I go to bed at 10 o'clock."),
      v("every day", "each day without exception", "todos os dias", "I study English every day."),
      v("o'clock", "used to say the exact hour", "em ponto (horas)", "School starts at 8 o'clock."),
    ],
    warmUpQuestions: [
      "What time do you wake up?",
      "What do you eat for breakfast?",
      "What do you do after school or work?",
      "What time do you go to bed?",
      "Do you have the same routine every day?",
    ],
    warmUpQuestionsPt: [
      "A que horas você acorda?",
      "O que você come no café da manhã?",
      "O que você faz depois da escola ou do trabalho?",
      "A que horas você vai dormir?",
      "Você tem a mesma rotina todos os dias?",
    ],
    sentenceFrames: [
      "I wake up at ___ o'clock.",
      "I have breakfast at ___.",
      "I go to ___ by ___.",
      "In the evening, I ___.",
      "I go to bed at ___.",
    ],
    rolePlayScenario: "Tell your teacher about your typical Monday. They will ask questions about your routine.",
    rolePlayRoles: ["Student", "Teacher"],
    practicePrompts: [
      "Say three things you do every morning in order.",
      "Complete: 'I wake up at ___ and I ___.'",
      "What time do you have lunch? Say a full sentence.",
      "Describe your evening routine in 3 sentences.",
      "Say one thing you do and one thing you don't do every day.",
    ],
    grammarPoints: ["Simple present (I wake up, I eat)", "Time expressions (at, every day, in the morning)", "Adverbs of frequency (always, usually, never)"],
    grammarNote: "Use the **simple present** for habits and routines: *I wake up at 7. She has breakfast at 8.* Don't forget the **-s** for he/she/it: *He goes to school. She eats breakfast.* Use **at** for times: *at 7 o'clock, at noon.*",
  },

  "food & drink": {
    vocab: [
      v("water", "the clear drink essential for life", "água", "I drink water every day."),
      v("bread", "a common baked food made from flour", "pão", "I eat bread for breakfast."),
      v("rice", "a common grain eaten with many meals", "arroz", "We have rice for lunch every day."),
      v("meat / chicken / fish", "types of protein food", "carne / frango / peixe", "I like chicken, but I don't eat fish."),
      v("fruit", "sweet food that grows on trees or plants", "fruta", "My favourite fruit is mango."),
      v("milk", "the white drink from cows", "leite", "I drink milk every morning."),
      v("coffee", "a hot dark drink made from beans", "café", "Brazilians love coffee!"),
      v("eat", "to put food in your mouth", "comer", "I eat three meals a day."),
      v("drink", "to put liquid in your mouth", "beber / tomar", "I drink a lot of water."),
      v("I like / I don't like", "expressing food preferences", "Eu gosto de / Eu não gosto de", "I like pizza. I don't like mushrooms."),
    ],
    warmUpQuestions: [
      "What is your favourite food?",
      "What do you eat for breakfast?",
      "Do you like to cook?",
      "What food do you eat every day?",
      "What food do you NOT like?",
    ],
    warmUpQuestionsPt: [
      "Qual é a sua comida favorita?",
      "O que você come no café da manhã?",
      "Você gosta de cozinhar?",
      "Que comida você come todos os dias?",
      "De qual comida você NÃO gosta?",
    ],
    sentenceFrames: [
      "My favourite food is ___.",
      "I like ___ but I don't like ___.",
      "I eat ___ for breakfast / lunch / dinner.",
      "I drink ___ every day.",
      "In Brazil, we usually eat ___.",
    ],
    rolePlayScenario: "You are in a café. Order food and drink for yourself and a friend.",
    rolePlayRoles: ["Customer", "Waiter / Waitress"],
    practicePrompts: [
      "Name five foods you like. Say: 'I like ___.'",
      "Name two foods you don't like. Say: 'I don't like ___.'",
      "Say what you eat for breakfast, lunch, and dinner.",
      "Complete: 'My favourite drink is ___.'",
      "Say one food that is typical in Brazil.",
    ],
    grammarPoints: ["Simple present (I eat, I drink, I like)", "Verb to like + noun", "Countable and uncountable nouns"],
    grammarNote: "Use **like** to say what you enjoy: *I like rice. She likes coffee.* For things you don't enjoy, say **don't like**: *I don't like mushrooms.* Remember: some foods are uncountable — *water, rice, bread* (no 's'). Others are countable — *an apple, two oranges.*",
  },

  "my home": {
    vocab: [
      v("bedroom", "the room where you sleep", "quarto", "My bedroom is small but comfortable."),
      v("kitchen", "the room where you cook food", "cozinha", "My mother is in the kitchen."),
      v("bathroom", "the room with the toilet and shower", "banheiro", "The bathroom is next to the bedroom."),
      v("living room", "the main room for relaxing", "sala de estar", "We watch TV in the living room."),
      v("table", "a flat surface on legs for eating or working", "mesa", "We eat at the table together."),
      v("chair", "a seat with a back", "cadeira", "There are four chairs around the table."),
      v("door", "the entrance to a room or house", "porta", "Please close the door."),
      v("window", "the glass opening in a wall for light", "janela", "I open the window in the morning."),
      v("big / small", "size adjectives", "grande / pequeno", "My house is small but my garden is big."),
      v("there is / there are", "to say what exists in a place", "há / existe(m)", "There is a sofa in the living room. There are two bedrooms."),
    ],
    warmUpQuestions: [
      "How many rooms does your home have?",
      "Where do you study or work at home?",
      "What is your favourite room?",
      "Is your home big or small?",
      "Do you live in a house or an apartment?",
    ],
    warmUpQuestionsPt: [
      "Quantos cômodos tem a sua casa?",
      "Onde você estuda ou trabalha em casa?",
      "Qual é o seu cômodo favorito?",
      "A sua casa é grande ou pequena?",
      "Você mora em uma casa ou apartamento?",
    ],
    sentenceFrames: [
      "My home has ___ bedrooms and ___ bathroom(s).",
      "There is a ___ in the ___.",
      "My favourite room is the ___ because ___.",
      "In my bedroom, there is/are ___.",
      "My home is ___ (big/small/old/new).",
    ],
    rolePlayScenario: "Describe your home to a new friend who is coming to visit. Tell them about the rooms and where things are.",
    rolePlayRoles: ["You (describing your home)", "Friend (asking questions)"],
    practicePrompts: [
      "Say: 'My home has ___ rooms.'",
      "Name three things in your bedroom.",
      "Complete: 'There is a ___ in my ___.'",
      "Say one thing you love about your home.",
      "Describe your living room in two sentences.",
    ],
    grammarPoints: ["There is / There are", "Prepositions of place (in, on, next to)", "Adjectives (big, small, old, new)"],
    grammarNote: "Use **there is** for one thing and **there are** for more than one: *There is a table. There are four chairs.* Use **in** for inside a room: *in the kitchen, in the bedroom.* Adjectives come before the noun: *a big kitchen, a small bedroom.*",
  },

  "animals": {
    vocab: [
      v("dog", "a common pet that barks", "cachorro", "I have a dog. His name is Rex."),
      v("cat", "a common pet that meows", "gato", "My cat sleeps all day."),
      v("bird", "an animal with wings and feathers", "pássaro", "There is a beautiful bird in the garden."),
      v("fish", "an animal that lives in water", "peixe", "I have three fish in a tank."),
      v("horse", "a large animal used for riding", "cavalo", "The horse is very fast."),
      v("cow", "a large farm animal that gives milk", "vaca", "Cows eat grass."),
      v("rabbit", "a small furry animal with long ears", "coelho", "My sister has a white rabbit."),
      v("elephant", "the largest land animal with a trunk", "elefante", "Elephants are very intelligent."),
      v("big / small / fast / slow", "animal describing words", "grande / pequeno / rápido / lento", "A cheetah is very fast. A turtle is very slow."),
      v("I have a pet", "to say you own an animal", "Eu tenho um animal de estimação", "I have a pet. It is a black cat."),
    ],
    warmUpQuestions: [
      "Do you have a pet? What is it?",
      "What is your favourite animal?",
      "Are you afraid of any animal?",
      "What animals live near your home?",
      "Can you name three animals in English?",
    ],
    warmUpQuestionsPt: [
      "Você tem um animal de estimação? Qual é?",
      "Qual é o seu animal favorito?",
      "Você tem medo de algum animal?",
      "Quais animais vivem perto da sua casa?",
      "Você consegue nomear três animais em inglês?",
    ],
    sentenceFrames: [
      "My favourite animal is a ___ because ___.",
      "I have a ___. It is ___ (colour/size).",
      "A ___ is ___ (adjective). It lives in ___.",
      "I like ___ but I am afraid of ___.",
      "A ___ eats ___.",
    ],
    rolePlayScenario: "You are at a pet shop. Ask the assistant about two different animals. Find out what they eat and how big they get.",
    rolePlayRoles: ["Customer", "Pet shop assistant"],
    practicePrompts: [
      "Name five animals you know in English.",
      "Describe your pet or your favourite animal: colour, size, what it eats.",
      "Complete: 'A ___ is ___ and it ___.'",
      "Say one animal that is big and one that is small.",
      "Say: 'I have/don't have a pet. My favourite animal is ___.'",
    ],
    grammarPoints: ["Simple present (it eats, it lives)", "Adjectives (big, small, fast, slow)", "Articles (a/an)"],
    grammarNote: "Use **a** before consonant sounds and **an** before vowel sounds: *a dog, a cat, an elephant, an owl.* Use **it** for animals when the gender is unknown: *My cat is black. It sleeps a lot.* Simple present for facts about animals: *A cow eats grass. Elephants live in Africa.*",
  },

  "the weather": {
    vocab: [
      v("sunny", "when there is bright sun", "ensolarado", "Today is sunny and warm."),
      v("rainy / it's raining", "when rain falls from the sky", "chuvoso / está chovendo", "It's raining. Take an umbrella!"),
      v("cloudy", "when the sky is covered with clouds", "nublado", "It's cloudy today. No sun."),
      v("hot", "when the temperature is high", "quente", "Brazil is very hot in summer."),
      v("cold", "when the temperature is low", "frio", "It's cold today. I need a jacket."),
      v("windy", "when the wind is strong", "ventoso / com vento", "It's very windy. Hold your hat!"),
      v("warm", "pleasantly hot, not too cold", "quente / agradável", "Spring is warm and beautiful."),
      v("What is the weather like?", "how to ask about the weather", "Como está o tempo?", "What is the weather like today?"),
      v("It's ___", "structure to describe the weather", "Está ___", "It's sunny. It's cold. It's raining."),
      v("temperature", "how hot or cold something is", "temperatura", "The temperature today is 30 degrees."),
    ],
    warmUpQuestions: [
      "What is the weather like today?",
      "Do you prefer hot or cold weather?",
      "What is the weather usually like in your city?",
      "What do you do on a rainy day?",
      "What is your favourite season?",
    ],
    warmUpQuestionsPt: [
      "Como está o tempo hoje?",
      "Você prefere clima quente ou frio?",
      "Como normalmente é o tempo na sua cidade?",
      "O que você faz em um dia chuvoso?",
      "Qual é a sua estação favorita?",
    ],
    sentenceFrames: [
      "Today it is ___.",
      "I like ___ weather because ___.",
      "When it is ___, I ___.",
      "In ___ (city), the weather is usually ___.",
      "It is ___ degrees today.",
    ],
    rolePlayScenario: "You call a friend to make plans for the weekend. Talk about the weather and decide what to do based on it.",
    rolePlayRoles: ["You", "Friend"],
    practicePrompts: [
      "Look outside or imagine the weather now. Say two sentences about it.",
      "Complete: 'It is ___ today. I am wearing ___.'",
      "Name three types of weather in English.",
      "Say what you like to do when it is sunny / rainy.",
      "Describe the weather in your city in winter and in summer.",
    ],
    grammarPoints: ["It is + adjective (It's hot)", "Present continuous (It's raining)", "Simple present for facts"],
    grammarNote: "To talk about weather, use **It is** + adjective: *It's sunny. It's cold.* For actions happening now, use **It's + -ing**: *It's raining. It's snowing.* Notice we always use **it** for weather — there is no real subject, it's just a grammar rule in English.",
  },

  "shopping & prices": {
    vocab: [
      v("shop / store", "a place where you buy things", "loja", "I go to the shop every Saturday."),
      v("How much is this?", "question to ask the price", "Quanto custa isso?", "Excuse me, how much is this shirt?"),
      v("price", "the amount of money something costs", "preço", "The price of this book is 20 reais."),
      v("cheap", "low in price, not expensive", "barato", "This is cheap! Only five reais."),
      v("expensive", "high in price", "caro", "That jacket is very expensive."),
      v("I want / I'd like", "how to ask for something politely", "Eu quero / Eu gostaria de", "I'd like a coffee, please."),
      v("pay", "to give money for something", "pagar", "I pay by card or cash."),
      v("money", "coins and notes used to buy things", "dinheiro", "I don't have money today."),
      v("big / small size", "asking for clothing size", "tamanho grande / pequeno", "Do you have this in a small size?"),
      v("Thank you / Here you go", "polite phrases in a shop", "Obrigado(a) / Aqui está", "Thank you! — Here you go, have a nice day!"),
    ],
    warmUpQuestions: [
      "Do you like shopping? Why?",
      "Where do you usually shop — online or in a store?",
      "What was the last thing you bought?",
      "Do you think shopping in English is easy or hard?",
      "What is something cheap you buy every week?",
    ],
    warmUpQuestionsPt: [
      "Você gosta de fazer compras? Por quê?",
      "Onde você costuma comprar — online ou em loja?",
      "Qual foi a última coisa que você comprou?",
      "Você acha que comprar em inglês é fácil ou difícil?",
      "O que é algo barato que você compra toda semana?",
    ],
    sentenceFrames: [
      "How much is this ___?",
      "I'd like ___, please.",
      "This is too expensive. Do you have something ___?",
      "I want to pay by ___.",
      "This is ___ (cheap / expensive).",
    ],
    rolePlayScenario: "You are in a clothes shop. Ask about prices, find something in your size, and buy it.",
    rolePlayRoles: ["Customer", "Shop assistant"],
    practicePrompts: [
      "Say: 'How much is this ___?'",
      "Practice: 'I'd like a ___, please. How much is it?'",
      "Name something cheap and something expensive in English.",
      "Say how you like to pay: card or cash?",
      "Complete: 'This shop is ___ because ___.'",
    ],
    grammarPoints: ["How much is/are?", "I'd like (polite requests)", "Adjectives (cheap, expensive, big, small)"],
    grammarNote: "Use **How much is this?** for one item and **How much are these?** for more than one. **I'd like** is more polite than **I want**: *I'd like a coffee, please.* To say something costs a lot, say **expensive**; to say it costs a little, say **cheap**.",
  },

  "days, months & seasons": {
    vocab: [
      v("Monday / Tuesday / Wednesday", "first three days of the week", "segunda / terça / quarta", "My class is on Monday and Wednesday."),
      v("Thursday / Friday / Saturday / Sunday", "other days of the week", "quinta / sexta / sábado / domingo", "I rest on Saturday and Sunday."),
      v("January / February / March", "first three months", "janeiro / fevereiro / março", "My birthday is in January."),
      v("spring / summer", "warm seasons", "primavera / verão", "Summer in Brazil is very hot."),
      v("autumn / fall / winter", "cooler seasons", "outono / inverno", "Winter in the south is cold."),
      v("today / tomorrow / yesterday", "time words", "hoje / amanhã / ontem", "Today is Monday. Yesterday was Sunday."),
      v("this week / next week", "week reference", "esta semana / semana que vem", "I have an exam next week."),
      v("in January / on Monday", "prepositions with time", "em janeiro / na segunda", "School starts in February. My class is on Friday."),
      v("What day is it?", "question about the current day", "Que dia é hoje?", "What day is it today? — It's Tuesday."),
      v("birthday", "the day you were born", "aniversário", "My birthday is in July."),
    ],
    warmUpQuestions: [
      "What day is it today?",
      "What month is your birthday?",
      "What is your favourite day of the week?",
      "What season do you like best?",
      "What do you do on Sundays?",
    ],
    warmUpQuestionsPt: [
      "Que dia é hoje?",
      "Em que mês é o seu aniversário?",
      "Qual é o seu dia favorito da semana?",
      "Qual estação você mais gosta?",
      "O que você faz nos domingos?",
    ],
    sentenceFrames: [
      "Today is ___.",
      "My birthday is in ___.",
      "On ___ I usually ___.",
      "My favourite season is ___ because ___.",
      "Next ___ I am going to ___.",
    ],
    rolePlayScenario: "Make a plan with a friend for next week. Agree on a day and time to meet.",
    rolePlayRoles: ["You", "Friend"],
    practicePrompts: [
      "Say all seven days of the week in order.",
      "Say the month of your birthday: 'My birthday is in ___.'",
      "Name the four seasons and one word about each.",
      "Complete: 'On Saturdays, I ___.'",
      "Say today's full date: day + date + month.",
    ],
    grammarPoints: ["Days of the week", "Months", "Prepositions of time (in, on, at)"],
    grammarNote: "Use **on** with days: *on Monday, on Friday.* Use **in** with months and seasons: *in January, in summer.* Use **at** with exact times: *at 3 o'clock, at noon.* Days and months always start with a **capital letter** in English: Monday, January.",
  },

  "school & classroom": {
    vocab: [
      v("teacher", "the person who teaches the class", "professor(a)", "My English teacher is very patient."),
      v("student", "a person who learns at school", "aluno(a)", "I am a student. There are 20 students in the class."),
      v("book", "a set of printed pages for reading or studying", "livro", "Open your book to page 10."),
      v("pen / pencil", "tools for writing", "caneta / lápis", "Can I borrow your pen?"),
      v("notebook", "a book for writing notes", "caderno", "Write it in your notebook."),
      v("desk", "a table for studying or writing", "carteira", "Sit at your desk, please."),
      v("class / lesson", "a time for learning with a teacher", "aula", "English class starts at 9 o'clock."),
      v("homework", "work done at home for school", "dever de casa / tarefa", "Do your homework tonight."),
      v("I don't understand", "saying you need help", "Eu não entendo", "I don't understand. Can you repeat, please?"),
      v("Can you repeat, please?", "asking someone to say something again", "Você pode repetir, por favor?", "Can you repeat that? I didn't hear."),
    ],
    warmUpQuestions: [
      "What is your favourite subject at school?",
      "What do you usually bring to class?",
      "Do you like homework? Why or why not?",
      "Who is your favourite teacher?",
      "What time does your class start?",
    ],
    warmUpQuestionsPt: [
      "Qual é a sua matéria favorita na escola?",
      "O que você geralmente traz para a aula?",
      "Você gosta de dever de casa? Por quê?",
      "Quem é o seu professor favorito?",
      "A que horas começa a sua aula?",
    ],
    sentenceFrames: [
      "My ___ class is at ___ o'clock.",
      "I have a ___ (pen/book/notebook) in my bag.",
      "Can you repeat ___, please?",
      "I don't understand ___. Can you explain?",
      "My favourite subject is ___ because ___.",
    ],
    rolePlayScenario: "You arrive late to class. Apologise to the teacher and ask what page the class is on.",
    rolePlayRoles: ["Late student", "Teacher"],
    practicePrompts: [
      "Name five things in your classroom right now.",
      "Say: 'I don't understand ___. Can you repeat, please?'",
      "Complete: 'My English class is on ___ at ___.'",
      "Say what you bring to class every day.",
      "Say one thing you like and one thing you find difficult about English class.",
    ],
    grammarPoints: ["Imperatives (Open, Write, Sit)", "Can for requests (Can you repeat?)", "Simple present for schedules"],
    grammarNote: "Use **Can you...?** to make polite requests: *Can you repeat that? Can you explain?* **Imperatives** give instructions — no subject needed: *Open your book. Write the answer. Listen carefully.* In English, school subjects don't use an article: *I study English* (not *the English*).",
  },

  "my body": {
    vocab: [
      v("head", "the top part of your body", "cabeça", "My head hurts. I have a headache."),
      v("eyes", "the parts of your face you see with", "olhos", "I have brown eyes."),
      v("nose", "the part in the middle of your face for breathing and smelling", "nariz", "My nose is cold."),
      v("mouth", "the opening in your face for eating and speaking", "boca", "Open your mouth wide."),
      v("ears", "the parts on the sides of your head for hearing", "orelhas", "I listen with my ears."),
      v("arms", "the limbs from your shoulders to your hands", "braços", "She has strong arms."),
      v("hands", "the parts at the end of your arms", "mãos", "Wash your hands before eating."),
      v("legs", "the limbs you use to walk", "pernas", "My legs are tired after running."),
      v("I have a ___ ache", "to say a part of your body hurts", "Eu estou com dor de ___", "I have a stomachache. I have a headache."),
      v("touch your ___", "instruction to point to a body part", "toque no(a) ___", "Touch your nose. Touch your ears."),
    ],
    warmUpQuestions: [
      "Can you point to five parts of your body and say them in English?",
      "Do you have any aches or pains today?",
      "What colour are your eyes?",
      "What body part do you use most when you study?",
      "How do you keep your body healthy?",
    ],
    warmUpQuestionsPt: [
      "Você consegue apontar cinco partes do corpo e dizê-las em inglês?",
      "Você está com alguma dor hoje?",
      "De que cor são seus olhos?",
      "Qual parte do corpo você usa mais quando estuda?",
      "Como você mantém o seu corpo saudável?",
    ],
    sentenceFrames: [
      "I have ___ eyes and ___ hair.",
      "I use my ___ to ___.",
      "My ___ hurts today.",
      "Touch your ___ — now touch your ___.",
      "I have two ___ and one ___.",
    ],
    rolePlayScenario: "You are at the doctor's. Tell the doctor where you have pain. The doctor asks questions.",
    rolePlayRoles: ["Patient", "Doctor"],
    practicePrompts: [
      "Point to five body parts and say each one in English.",
      "Complete: 'I have ___ eyes and ___ hair.'",
      "Say: 'My ___ hurts.'",
      "Describe someone in your family using body parts.",
      "Say two things your hands do and two things your legs do.",
    ],
    grammarPoints: ["I have (to describe body)", "Plurals (two eyes, two ears)", "My body / possessives"],
    grammarNote: "Use **I have** to describe your body: *I have brown eyes. I have two arms.* For pain, say **I have a ___ ache**: *I have a headache / stomachache / toothache.* Some body parts come in pairs and are always plural: *eyes, ears, hands, legs, feet* — use **two** or just the plural form.",
  },

  "clothes": {
    vocab: [
      v("shirt / T-shirt", "a top for the upper body", "camisa / camiseta", "He is wearing a blue shirt."),
      v("trousers / pants", "clothing for the lower body", "calça", "I wear black trousers to work."),
      v("dress", "a one-piece garment for women/girls", "vestido", "She has a beautiful red dress."),
      v("shoes", "footwear for your feet", "sapatos", "I need new shoes. These are old."),
      v("jacket / coat", "outer clothing for warmth", "jaqueta / casaco", "Take your coat — it's cold outside."),
      v("hat", "something worn on the head", "chapéu / boné", "He always wears a hat in the sun."),
      v("socks", "soft covering worn on feet inside shoes", "meias", "I wear white socks every day."),
      v("I'm wearing ___", "to describe what you have on now", "Eu estou usando/vestindo ___", "Today I'm wearing a blue T-shirt and jeans."),
      v("What colour is it?", "asking about the colour of clothing", "De que cor é?", "What colour is your jacket? — It's black."),
      v("size", "how big or small a piece of clothing is", "tamanho", "What size do you wear? I wear medium."),
    ],
    warmUpQuestions: [
      "What are you wearing today?",
      "What is your favourite colour to wear?",
      "Do you like shopping for clothes?",
      "What do you wear to work or school?",
      "Do you prefer casual or formal clothes?",
    ],
    warmUpQuestionsPt: [
      "O que você está usando hoje?",
      "Qual é a sua cor favorita para usar?",
      "Você gosta de comprar roupas?",
      "O que você usa para trabalhar ou estudar?",
      "Você prefere roupas casuais ou formais?",
    ],
    sentenceFrames: [
      "Today I'm wearing ___.",
      "My favourite ___ is ___ (colour).",
      "I usually wear ___ to ___.",
      "This ___ is ___ (too big / too small / perfect).",
      "I like to wear ___ because ___.",
    ],
    rolePlayScenario: "You are in a clothes shop. Describe what you are looking for and try something on.",
    rolePlayRoles: ["Customer", "Shop assistant"],
    practicePrompts: [
      "Describe what you are wearing right now.",
      "Name five items of clothing in English.",
      "Complete: 'I usually wear ___ when I go to ___.'",
      "Say your favourite outfit and its colours.",
      "Say what you wear in hot weather and in cold weather.",
    ],
    grammarPoints: ["Present continuous (I'm wearing)", "Colours as adjectives", "Adjectives before nouns"],
    grammarNote: "Use **present continuous** to talk about what you are wearing NOW: *I'm wearing a red dress. He's wearing blue jeans.* Remember, adjectives come BEFORE the noun in English: *a black jacket* (not *a jacket black*). For ongoing states, use **I wear** (simple present) for habits: *I always wear glasses.*",
  },

  "hobbies i like": {
    vocab: [
      v("I like ___", "to express enjoyment", "Eu gosto de ___", "I like reading and cooking."),
      v("I love ___", "to express strong enjoyment", "Eu amo ___", "I love playing football!"),
      v("I don't like ___", "to express dislike", "Eu não gosto de ___", "I don't like getting up early."),
      v("play (sport / instrument)", "to do sport or music", "jogar / tocar", "I play football. I play guitar."),
      v("read", "to look at and understand written words", "ler", "I read books every night."),
      v("watch", "to look at (TV, films)", "assistir", "I love watching films on weekends."),
      v("listen to music", "to hear music for enjoyment", "ouvir música", "I listen to music when I exercise."),
      v("cook", "to prepare food using heat", "cozinhar", "I cook dinner for my family every day."),
      v("draw / paint", "to make pictures with pencil or paint", "desenhar / pintar", "I draw in my free time."),
      v("free time", "time when you are not working or studying", "tempo livre", "In my free time, I read books."),
    ],
    warmUpQuestions: [
      "What do you like to do in your free time?",
      "Do you have a favourite sport or activity?",
      "How many hours a week do you have for hobbies?",
      "What is one hobby you want to learn?",
      "Do you prefer indoor or outdoor activities?",
    ],
    warmUpQuestionsPt: [
      "O que você gosta de fazer no seu tempo livre?",
      "Você tem um esporte ou atividade favorita?",
      "Quantas horas por semana você tem para hobbies?",
      "Qual é um hobby que você quer aprender?",
      "Você prefere atividades ao ar livre ou em casa?",
    ],
    sentenceFrames: [
      "I like ___ because ___.",
      "I love ___ in my free time.",
      "I don't like ___ very much.",
      "On weekends, I usually ___.",
      "I want to learn how to ___.",
    ],
    rolePlayScenario: "You meet someone new. Talk about your hobbies. Find out two things you have in common.",
    rolePlayRoles: ["You", "New friend"],
    practicePrompts: [
      "Name three things you like to do. Say: 'I like ___.'",
      "Say one hobby you love and one you don't like.",
      "Complete: 'In my free time, I like to ___.'",
      "Say something you want to learn how to do.",
      "Say what you do on a typical Saturday.",
    ],
    grammarPoints: ["I like + -ing (I like reading)", "I love / I don't like", "Simple present for habits"],
    grammarNote: "After **like, love, enjoy**, use the **-ing** form of the verb: *I like swimming. I love cooking.* For things you dislike, say **I don't like + -ing**: *I don't like running.* You can also say **I like to + verb**: *I like to read.* Both are correct — choose what feels natural.",
  },
};

/** Return topic-specific A1 content or undefined if the topic is not in the lookup. */
export function getA1TopicContent(topic: string): A1MockContent | undefined {
  const key = topic.trim().toLowerCase();
  // Exact match first
  if (A1_CONTENT[key]) return A1_CONTENT[key];
  // Partial match (topic may have trailing punctuation or minor variation)
  const found = Object.keys(A1_CONTENT).find(
    (k) => key.includes(k) || k.includes(key),
  );
  return found ? A1_CONTENT[found] : undefined;
}
